package dgSofta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import dgSofta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.28 20:46:19 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuloksetTest {



  // Generated by ComTest BEGIN
  /** testLisaa49 */
  @Test
  public void testLisaa49() {    // Tulokset: 49
    Tulokset tulokset = new Tulokset(); 
    Tulos tulos1 = new Tulos(), tulos2 = new Tulos(); 
    assertEquals("From: Tulokset line: 52", 0, tulokset.getLkm()); 
    tulokset.lisaa(tulos1); assertEquals("From: Tulokset line: 53", 1, tulokset.getLkm()); 
    tulokset.lisaa(tulos2); assertEquals("From: Tulokset line: 54", 2, tulokset.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm67 */
  @Test
  public void testGetLkm67() {    // Tulokset: 67
    Tulokset tulokset = new Tulokset(); 
    Tulos tulos1 = new Tulos(), tulos2 = new Tulos(); 
    assertEquals("From: Tulokset line: 70", 0, tulokset.getLkm()); 
    tulokset.lisaa(tulos1); assertEquals("From: Tulokset line: 71", 1, tulokset.getLkm()); 
    tulokset.lisaa(tulos2); assertEquals("From: Tulokset line: 72", 2, tulokset.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaTulokset83 */
  @Test
  public void testAnnaTulokset83() {    // Tulokset: 83
    Tulokset tulokset = new Tulokset(); 
    Tulos tulos1 = new Tulos(), tulos2 = new Tulos(), tulos3 = new Tulos(); 
    tulos1.setId(1); tulos2.setId(1); tulos3.setId(2); 
    tulokset.lisaa(tulos1); tulokset.lisaa(tulos2); tulokset.lisaa(tulos3); 
    assertEquals("From: Tulokset line: 88", 2, tulokset.annaTulokset(1).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista172 */
  @Test
  public void testPoista172() {    // Tulokset: 172
    Tulokset tulokset = new Tulokset(); 
    Tulos tulos1 = new Tulos(), tulos2 = new Tulos(), tulos3 = new Tulos(); 
    tulos1.setId(1); tulos2.setId(1); tulos3.setId(2); 
    tulokset.lisaa(tulos1); tulokset.lisaa(tulos2); tulokset.lisaa(tulos3); 
    tulokset.poista(tulos3); 
    assertEquals("From: Tulokset line: 178", 2, tulokset.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaRadanTulokset192 */
  @Test
  public void testPoistaRadanTulokset192() {    // Tulokset: 192
    Tulokset tulokset = new Tulokset(); 
    Tulos tulos1 = new Tulos(), tulos2 = new Tulos(), tulos3 = new Tulos(); 
    tulos1.setId(1); tulos2.setId(1); tulos3.setId(2); 
    tulokset.lisaa(tulos1); tulokset.lisaa(tulos2); tulokset.lisaa(tulos3); 
    assertEquals("From: Tulokset line: 197", 3, tulokset.getLkm()); 
    assertEquals("From: Tulokset line: 198", 2, tulokset.poistaRadanTulokset(1)); 
    assertEquals("From: Tulokset line: 199", 1, tulokset.getLkm()); 
  } // Generated by ComTest END
}