package dgSofta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import dgSofta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.28 20:27:20 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TulosTest {



  // Generated by ComTest BEGIN
  /** testGetId64 */
  @Test
  public void testGetId64() {    // Tulos: 64
    Tulos tulos = new Tulos(); 
    tulos.setId(3); 
    assertEquals("From: Tulos line: 67", 3, tulos.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse139 */
  @Test
  public void testParse139() {    // Tulos: 139
    Tulos tulos = new Tulos(); 
    assertEquals("From: Tulos line: 141", true, tulos.toString().equals("0||0|")); 
    tulos.parse("1|25.3.2018|65"); 
    tulos.toString().equals("1|25.3.2018|65|"); 
  } // Generated by ComTest END
}